Refactor functions

diff --git a/app/create_nomi b/app/create_nomi
--- a/app/create_nomi
+++ b/app/create_nomi
@@ -134,31 +134,13 @@ fi
 # Trap to function when we exit
 trap "cleanup" EXIT INT
 
-# Define cleanup function
+# Cleanup function
 function cleanup() {
     exit_code=$?
     exit $exit_code
 }
 
-echo "==========================================================================="
-echo "============================= Create a Nomi ==============================="
-echo "==========================================================================="
-echo
-echo "Use this script to create a new Nomi, or to verify an existing Nomi's"
-echo "configuration."
-echo
-echo "If you ever want to quit the script, simply press CTRL+C together"
-echo
-
-# Check if Docker is installed
-if ! command -v docker >/dev/null 2>&1; then
-    echo "Could not find Docker. Please re-run the installation script"
-    exit 1
-fi
-
-SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
-# Function to prompt for and confirm user input
+# Prompt for and confirm user input
 prompt_confirm() {
     read -r -p "$1 [y/N] " RESPONSE </dev/tty
     case "$RESPONSE" in
@@ -171,7 +153,7 @@ prompt_confirm() {
     esac
 }
 
-# Function to prompt for variable values
+# Prompt for variable values
 prompt_variable() {
     local var_name=$1
     local current_value=$2
@@ -179,6 +161,7 @@ prompt_variable() {
     echo "${value:-$current_value}"
 }
 
+# Get a script and make it executable based on the OS name
 function get_script() {
     local source_file="$1"
     local destination_dir="$2"
@@ -207,40 +190,7 @@ function get_script() {
     chmod +x "$destination_file"
 }
 
-# Find all .conf files and extract NOMI_NAME
-conf_files=()
-nomi_names=()
-while IFS= read -r -d '' file; do
-    conf_files+=("$file")
-    nomi_name=$(grep -m1 '^NOMI_NAME=' "$file" | cut -d '=' -f2)
-    nomi_names+=("$NOMI_NAME")
-done < <(find . -maxdepth 1 -name '*.conf' -print0)
-
-# List NOMI names if there are any, or prompt to create new
-if [ "${#conf_files[@]}" -eq 0 ]; then
-    echo "No Nomi configuration files found."
-    prompt_confirm "Do you want to create a new Nomi?" && create_new_nomi
-else
-    echo "These Nomi configuration files were found:"
-    for i in "${!nomi_names[@]}"; do
-        echo "$((i+1)). ${nomi_names[$i]}"
-    done
-
-    read -r -p "Choose a Nomi by number or type 'new' to create a new Nomi: " choice
-
-    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -le "${#nomi_names[@]}" ]; then
-        selected_nomi="${nomi_names[$((choice-1))]}"
-        selected_conf="${conf_files[$((choice-1))]}"
-        manage_existing_nomi "$selected_nomi" "$selected_conf"
-    elif [ "$choice" == "new" ]; then
-        create_new_nomi
-    else
-        echo "Invalid selection."
-        exit 1
-    fi
-fi
-
-# Function to manage existing Nomi configuration
+# Manage existing Nomi configuration file
 manage_existing_nomi() {
     local nomi_name=$1
     local conf_file=$2
@@ -272,7 +222,7 @@ manage_existing_nomi() {
     fi
 }
 
-# Function to create a new Nomi
+# Create new Nomi configuration file
 create_new_nomi() {
 
     while true; do
@@ -328,16 +278,55 @@ create_new_nomi() {
     fi
 }
 
-# Check for a configuration file
-if [ -f "$CONFIG_FILE" ]; then
-    # Inform user we've found the config file
-    echo "Found $NOMI_NAME's configuration file. Reading contents..."
-    source "$CONFIG_FILE"
-else
-    # No configuration file found. Ask the user to run create_nomi to set one up
-    echo "A configuration file for $NOMI_NAME was not found. Please re-run"
-    echo "the create_nomi script to set up $NOMI_NAME"
+echo "==========================================================================="
+echo "============================= Create a Nomi ==============================="
+echo "==========================================================================="
+echo
+echo "Use this script to create a new Nomi, or to verify an existing Nomi's"
+echo "configuration."
+echo
+echo "If you ever want to quit the script, simply press CTRL+C together"
+echo
+
+# Check if Docker is installed
+if ! command -v docker >/dev/null 2>&1; then
+    echo "Could not find Docker. Please re-run the installation script"
     exit 1
+fi
+
+SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+# Find all .conf files and extract NOMI_NAME
+conf_files=()
+nomi_names=()
+while IFS= read -r -d '' file; do
+    conf_files+=("$file")
+    nomi_name=$(grep -m1 '^NOMI_NAME=' "$file" | cut -d '=' -f2)
+    nomi_names+=("$NOMI_NAME")
+done < <(find . -maxdepth 1 -name '*.conf' -print0)
+
+# List NOMI names if there are any, or prompt to create new
+if [ "${#conf_files[@]}" -eq 0 ]; then
+    echo "No Nomi configuration files found."
+    prompt_confirm "Do you want to create a new Nomi?" && create_new_nomi
+else
+    echo "These Nomi configuration files were found:"
+    for i in "${!nomi_names[@]}"; do
+        echo "$((i+1)). ${nomi_names[$i]}"
+    done
+
+    read -r -p "Choose a Nomi by number or type 'new' to create a new Nomi: " choice
+
+    if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -le "${#nomi_names[@]}" ]; then
+        selected_nomi="${nomi_names[$((choice-1))]}"
+        selected_conf="${conf_files[$((choice-1))]}"
+        manage_existing_nomi "$selected_nomi" "$selected_conf"
+    elif [ "$choice" == "new" ]; then
+        create_new_nomi
+    else
+        echo "Invalid selection."
+        exit 1
+    fi
 fi
 
 echo "You may now close this window"
