Update setup

diff --git a/setup/setup b/setup/setup
--- a/setup/setup
+++ b/setup/setup
@@ -28,14 +28,14 @@ SET "DOCKER_IMAGE_NAME=nomi-config-setup"
 
 :: Check if Docker is installed
 docker --version >NUL 2>&1
-IF ERRORLEVEL 1 (
+IF %ERRORLEVEL% (
     ECHO Could not find Docker. Please re-run the installation script.
     GOTO CLEANUP
 )
 
 :: Check if Docker daemon is running
 docker info >NUL 2>&1
-IF ERRORLEVEL 1 (
+IF %ERRORLEVEL% (
     ECHO Docker is installed but the Docker daemon is not running.
     ECHO Please start Docker before continuing.
     GOTO CLEANUP
@@ -46,7 +46,7 @@ FOR /F "DELIMS=" %%I IN ('docker images -q %DOCKER_IMAGE_NAME%') DO SET IMAGE_ID
 IF NOT DEFINED IMAGE_ID (
     ECHO Setup Docker image ^(%DOCKER_IMAGE_NAME%^) not found. Building the image...
     FOR /F "TOKENS=*" %%I IN ('docker build -t %DOCKER_IMAGE_NAME% "%SETUP_DIR%" 2^>^&1') DO SET "DOCKER_BUILD_OUTPUT=%%I"
-    IF ERRORLEVEL 1 (
+    IF %ERRORLEVEL% (
         ECHO Error when building container: !DOCKER_BUILD_OUTPUT!
         GOTO CLEANUP
     )
@@ -60,10 +60,10 @@ IF NOT EXIST "%SETUP_DIR%\output" (
 
 :: Check if a Docker container already exists and remove it
 docker inspect --type=container %DOCKER_IMAGE_NAME% >NUL 2>&1
-IF NOT ERRORLEVEL 1 (
+IF NOT %ERRORLEVEL% (
     ECHO A Docker container for %NOMI_NAME% exists. Removing container...
     docker container rm %DOCKER_IMAGE_NAME% -f >NUL 2>&1
-    IF ERRORLEVEL 1 (
+    IF %ERRORLEVEL% (
         ECHO Error when removing container.
         GOTO CLEANUP
     )
@@ -85,7 +85,7 @@ IF %ERRORLEVEL% (
 
 :: Remove container once we're done to avoid confusion
 docker container rm %DOCKER_IMAGE_NAME% -f >NUL 2>&1
-IF ERRORLEVEL 1 (
+IF %ERRORLEVEL% (
     ECHO Error when removing container.
     GOTO CLEANUP
 )
@@ -259,22 +259,22 @@ echo
 # Run the Docker image with a mounted volume for output files
 docker run -it --name $DOCKER_IMAGE_NAME -v "$SETUP_DIR/output:/app/output" -e HOST=$(uname -s) "$DOCKER_IMAGE_NAME"
 EXIT_CODE=$?
-if [ $EXIT_CODE -ne 0 ]; then
-    echo "Error when running container: $EXIT_CODE"
-    exit 1
-fi
-
-# Remove the container once we're done to avoid confusion
-docker rm $DOCKER_IMAGE_NAME -f 2>&1 >/dev/null
-EXIT_CODE=$?
 if [[ $EXIT_CODE -ne 0 ]]; then
     if [[ $EXIT_CODE -eq 255 ]]; then
         echo "Operation cancelled."
         exit 1
     else
-        echo "Error when removing container: $EXIT_CODE"
+    echo "Error when running container: $EXIT_CODE"
         exit 1
     fi
+fi
+
+# Remove the container once we're done to avoid confusion
+docker rm -f "$DOCKER_IMAGE_NAME" 2>&1 >/dev/null
+EXIT_CODE=$?
+if [[ $EXIT_CODE -ne 0 ]]; then
+    echo "Error when removing container: $EXIT_CODE"
+    exit 1
 fi
 
 # Create the nomis folder if it doesn't exist.
